[package]
name = "andromeda"
version = "0.1.0"
authors = ["thealchemist17 <lucamancinelli17@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5"
nannou = "0.11.1"
colored =" 1.8.0"
